### PR TITLE
Fetching financials

### PR DESCRIPTION
**Pull request by ParadoxicalNerd**

### CODE REVIEW

**Comment by ParadoxicalNerd** [comment]
I finally got it to work with docker! It was a great learning experience!
I also synced my branch with main this way: https://stackoverflow.com/a/16330001/17005788. Please let me know if I messed up anything

**Comment by MaxDillon** [comment]
> I finally got it to work with docker! It was a great learning experience! I also synced my branch with main this way: https://stackoverflow.com/a/16330001/17005788. Please let me know if I messed up anything

Thats awesome! How are you liking it? I probably nearly overuse containerization just because I love it so much. 

The way you merged in main looks totally fine. And it's a realyl good thing to do once in a while on your branches, especially if there are a bunch of people actively working on the same thing. I as talking in class a bit ago about how some best practices recommend rebasing everything, but I think that's not super necesary and probably increases the risk of making some mistakes if you're not used to it.

**Comment by ParadoxicalNerd** [comment]
@MaxDillon I need a bit of help. For some reason, python datetime.datetime.now() is not returning time in the correct locale. I've tried manually setting the timezone, but even though it works in another python environment (that I'm running through another docker compose so its clean), it refuses to give the correct time.

**Comment by MaxDillon** [comment]
> @MaxDillon I need a bit of help. For some reason, python datetime.datetime.now() is not returning time in the correct locale. I've tried manually setting the timezone, but even though it works in another python environment (that I'm running through another docker compose so its clean), it refuses to give the correct time.

My guess, if you've tried everything else is that this is not a problem with the python, but it's instead a problem with postgres. It seems like the ZoneInfo is a pretty new addition to python, and I'm not exactly sure how psycopg handles it. It seems like the postgres datetime datatype has it's own unique way of handling timezones. 

If this is the problem, it seems like you could store the dates as utc time, you could create a SQL trigger to do something to time on insert, or maybe there's something else that can be done with inserting zoned times with psycopg and postgres.

I kinda tend towards the solution of just storing utc, but I understand that you want the new york stock exchange times, so idn

**Comment by ParadoxicalNerd** [comment]
What I was thinking is that I store the timestamp as Unix epoch so we can do the conversion on the frontend. What are your thoughts?

**Review by MaxDillon — APPROVED** [review]
Looks good! If you fel fine, merge it up

**Pull request merged**
